kind: PersistentVolume
apiVersion: v1
metadata:
  name: product-claim-api
  labels:
    pv: product-claim-api
spec:
  capacity:
    storage: 5Gi
  mountOptions:
  - vers=4
  - minorversion=0
  - noresvport
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 39c0c48dee-opf74.cn-shanghai.nas.aliyuncs.com
    path: "/api"   ###这个文件夹要提前在nfs下面创建好
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-claim-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      pv: product-claim-api
