---
apiVersion: v1
kind: Pod
metadata:
  name: website2
  labels:
    app: website
    role: frontend
spec:
  containers:
    - name: website
      image: nginx
      ports:
        - containerPort: 80