apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: allow-database2
spec:
  selector:
    matchLabels:
      role: frontend
  env:
    - name: DB_PORT2
      value: "6375"
  volumeMounts:
    - mountPath: /cache1
      name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
